package com.cbfacademy.apiassessment.dao;
import com.cbfacademy.apiassessment.model.StockTransaction;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

/*This class is an interface that defines a contract for how the StockTransaction 
enteties should interacting with thee data access layer for this project.
*/


public interface StockTransactionDao {
    //Inserting a new StockTransaction into the data store, and it requires both a UUID and the StockTransaction object  
    int insertStockTransaction(UUID id, StockTransaction transaction);

    //Default method to insert StockTransaction without specifying a UUID, rather it's generated by UUID.randomUUID()
    default int insertStockTransaction(StockTransaction transaction){
        return insertStockTransaction(UUID.randomUUID(), transaction);
    }
    //This method retrieves a list of all StockTransaction entities from the data store.
    List<StockTransaction> selectAllTransactions();

    //Method to return profit 
    Double profitCalculation(StockTransaction transaction);

    //Method to retrieve a transaction by id
    Optional<StockTransaction> selectTransactionById(UUID id);

    ////Method to delete a transaction from the data base/JSON using id 
    int deleteTransactionById(UUID id);

    ////Method to update a transaction from the data base/JSON using id 
    int updateTransactionById(UUID id, StockTransaction transaction);
}
